/**
 * Type definitions for the Book Creation Wizard
 * 
 * This file contains all TypeScript interfaces and types used throughout
 * the conversational book creation wizard feature.
 */

import type { BookStyle } from './BookStyle';

/**
 * Wizard step types
 * Defines the sequential steps in the book creation wizard
 */
export type WizardStep = 'welcome' | 'concept' | 'style' | 'characters' | 'summary';

/**
 * Wizard step constants
 */
export const WizardSteps = {
  WELCOME: 'welcome' as const,
  CONCEPT: 'concept' as const,
  STYLE: 'style' as const,
  CHARACTERS: 'characters' as const,
  SUMMARY: 'summary' as const
} as const;

/**
 * Message role types for conversation
 */
export type MessageRole = 'system' | 'user' | 'assistant';

/**
 * Message metadata types
 */
export type MessageType = 'suggestion' | 'question' | 'confirmation' | 'error';

/**
 * Message in the conversation
 */
export interface Message {
  /** Unique message identifier */
  id: string;
  
  /** Role of the message sender */
  role: MessageRole;
  
  /** Message content (supports markdown) */
  content: string;
  
  /** Timestamp when message was created */
  timestamp: Date;
  
  /** Optional metadata for special message types */
  metadata?: {
    /** Type of message for special handling */
    type?: MessageType;
    
    /** Additional data associated with the message */
    data?: any;
  };
}

/**
 * Book data being constructed during the wizard
 */
export interface WizardBookData {
  /** User's initial concept description */
  concept?: string;
  
  /** Generated or user-provided book title */
  title?: string;
  
  /** Book description */
  description?: string;
  
  /** Background setup for the story world */
  backgroundSetup?: string;
  
  /** Aspect ratio for images (e.g., "9:16", "3:4") */
  aspectRatio?: string;
  
  /** Visual style configuration */
  style?: BookStyle;
  
  /** Final refined prompt for the selected style */
  stylePrompt?: string;
  
  /** Characters created during the wizard */
  characters: CharacterProfile[];
}

/**
 * Style option generated by LLM with associated image
 */
export interface StyleOption {
  /** Unique identifier for this style option */
  id: string;
  
  /** Name/description of the style */
  name: string;
  
  /** Complete image generation prompt */
  prompt: string;
  
  /** URL of the generated sample image */
  imageUrl: string;
  
  /** Structured style configuration */
  style: BookStyle;
}

/**
 * Generated image with metadata
 */
export interface GeneratedImage {
  /** Unique image identifier */
  id: string;
  
  /** Image data URL or storage path */
  url: string;
  
  /** Prompt used to generate this image */
  prompt: string;
  
  /** When the image was generated */
  timestamp: Date;
}

/**
 * Single iteration in the style refinement process
 */
export interface RefinementIteration {
  /** User's feedback for refinement (e.g., "make it more cartoonish") */
  userFeedback: string;
  
  /** Modified prompt after applying feedback */
  modifiedPrompt: string;
  
  /** Images generated with the modified prompt */
  generatedImages: GeneratedImage[];
  
  /** When this refinement was performed */
  timestamp: Date;
}

/**
 * State for style refinement workflow
 */
export interface StyleRefinementState {
  /** Initial style options generated (3-5 variations) */
  initialOptions: StyleOption[];
  
  /** Currently selected style option */
  selectedOption?: StyleOption;
  
  /** History of refinement iterations */
  refinementHistory: RefinementIteration[];
  
  /** Current images being displayed (latest refinement) */
  currentImages: GeneratedImage[];
  
  /** Whether refinement is in progress */
  isRefining: boolean;
}

/**
 * Complete wizard state
 */
export interface WizardState {
  /** Current step in the wizard */
  currentStep: WizardStep;
  
  /** Conversation message history */
  messages: Message[];
  
  /** Book data being constructed */
  bookData: WizardBookData;
  
  /** Style refinement state */
  styleRefinement: StyleRefinementState;
  
  /** Whether an async operation is in progress */
  isProcessing: boolean;
  
  /** Current error message, if any */
  error: string | null;
}

/**
 * Concept analysis result from LLM
 */
export interface ConceptAnalysis {
  /** Identified themes in the concept */
  themes: string[];
  
  /** Suggested genres for the book */
  suggestedGenres: string[];
  
  /** Target audience description */
  targetAudience: string;
  
  /** Key visual elements identified */
  visualElements: string[];
}

/**
 * Book metadata generated from concept
 */
export interface BookMetadata {
  /** Suggested book title */
  title: string;
  
  /** Book description */
  description: string;
  
  /** Background setup for the story world */
  backgroundSetup: string;
}

/**
 * Style variation generated by LLM
 */
export interface StyleVariation {
  /** Name of this style variation */
  name: string;
  
  /** Art style description (e.g., "hand-painted watercolor") */
  artStyle: string;
  
  /** Color palette description */
  colorPalette: string;
  
  /** Overall visual theme */
  visualTheme: string;
  
  /** Character style description */
  characterStyle: string;
  
  /** Environment style description */
  environmentStyle: string;
  
  /** Complete image generation prompt */
  prompt: string;
}

/**
 * Persisted wizard state for localStorage
 */
export interface PersistedWizardState {
  /** Schema version for migration support */
  version: number;
  
  /** When the state was saved */
  timestamp: Date;
  
  /** The wizard state */
  state: WizardState;
  
  /** Temporary image IDs to clean up on completion/cancellation */
  temporaryImages: string[];
}

/**
 * Character profile with visual details
 */
export interface CharacterProfile {
  /** Character name */
  name: string;
  
  /** Character description */
  description: string;
  
  /** Detailed visual characteristics */
  visualDetails: {
    /** Physical appearance description */
    appearance: string;
    
    /** Clothing and accessories */
    clothing: string;
    
    /** Distinctive features that set them apart */
    distinctiveFeatures: string;
  };
}

/**
 * Props for wizard components
 */
export interface BookCreationWizardProps {
  /** Whether the wizard dialog is open */
  open: boolean;
  
  /** Callback when wizard is closed/cancelled */
  onClose: () => void;
  
  /** Callback when book creation is complete */
  onComplete: (bookId: string) => void;
}

/**
 * Result of a wizard operation
 */
export interface WizardOperationResult<T = void> {
  /** Whether the operation succeeded */
  success: boolean;
  
  /** Result data if successful */
  data?: T;
  
  /** Error message if failed */
  error?: string;
}
